"""Semantic retrieval and evidence-grounded knowledge conversation primitives."""

from .contracts import (
    AnswerEvidence,
    AnswerProvider,
    CancellationToken,
    EmbeddingBatch,
    EmbeddingProvider,
    GeneratedAnswer,
    GeneratedParagraph,
    ProviderCapabilities,
    ProviderDisclosure,
    ProviderError,
    RetrievalError,
    RetrievalPolicy,
    RetrievalRequest,
    RetrievalScope,
    RerankCandidate,
    RerankResult,
    RerankingProvider,
    ScopeDecision,
    build_provider_disclosure,
    scope_decision,
)
from .chunking import chunk_markdown_file, reidentify_note
from .index import INDEX_SCHEMA_VERSION, RetrievalIndex, StoredEmbedding
from .evaluation import FixtureResult, RetrievalEvaluation, RetrievalFixture, evaluate_retrieval
from .models import ChunkedNote, IndexedChunk, IndexedDocument
from .policy import load_retrieval_policy
from .search import HybridRetriever, RankingComponents, RetrievalEvidence, RetrievalResponse
from .service import IndexHealth, IndexProgress, IndexRecoveryPlan, IndexResult, RetrievalIndexService
from .providers import (
    DeterministicAnswerProvider,
    DeterministicEmbeddingProvider,
    DeterministicReranker,
    FailingAnswerProvider,
    UnavailableEmbeddingProvider,
)

__all__ = [
    "AnswerEvidence",
    "AnswerProvider",
    "ChunkedNote",
    "CancellationToken",
    "INDEX_SCHEMA_VERSION",
    "IndexHealth",
    "IndexProgress",
    "IndexRecoveryPlan",
    "IndexResult",
    "IndexedChunk",
    "IndexedDocument",
    "DeterministicAnswerProvider",
    "DeterministicEmbeddingProvider",
    "DeterministicReranker",
    "FailingAnswerProvider",
    "EmbeddingBatch",
    "EmbeddingProvider",
    "FixtureResult",
    "GeneratedAnswer",
    "GeneratedParagraph",
    "HybridRetriever",
    "ProviderCapabilities",
    "ProviderDisclosure",
    "ProviderError",
    "RankingComponents",
    "RetrievalError",
    "RetrievalEvaluation",
    "RetrievalEvidence",
    "RetrievalFixture",
    "RetrievalIndex",
    "RetrievalIndexService",
    "RetrievalPolicy",
    "RetrievalRequest",
    "RetrievalResponse",
    "RetrievalScope",
    "RerankCandidate",
    "RerankResult",
    "RerankingProvider",
    "ScopeDecision",
    "StoredEmbedding",
    "UnavailableEmbeddingProvider",
    "build_provider_disclosure",
    "chunk_markdown_file",
    "evaluate_retrieval",
    "load_retrieval_policy",
    "reidentify_note",
    "scope_decision",
]
