from .loader import (
    LoadedProposal,
    ProposalCollectionResult,
    ProposalLoadFinding,
    ProposalLoadResult,
    load_proposal_directory,
    load_proposals,
)
from .patches import (
    AnyPatchDocument,
    CreateFile,
    CreateGeneratedFile,
    CreateGeneratedFileV2,
    PatchDocument,
    PatchDocumentV2,
    PatchHumanFile,
    PatchOperation,
    PatchOperationV1,
    PatchOperationV2,
    PatchSchemaError,
    ReplaceGeneratedFile,
    ReplaceGeneratedFileV2,
    ReleaseGeneratedOwnershipV2,
    ReplaceManagedBlock,
    serialize_patch_document,
    serialize_patch_json_bytes,
    validate_patch_document,
)
from .schema import (
    ProposalMetadata,
    ProposalRisk,
    ProposalSchemaError,
    ProposalStatus,
    generate_proposal_id,
    serialize_metadata,
    validate_metadata,
    validate_proposal_id,
)
from .validation import (
    OperationPreflightResult,
    PreflightFinding,
    PreflightState,
    ProposalPreflightResult,
    preflight_proposal,
)

__all__ = [
    "AnyPatchDocument",
    "CreateFile",
    "CreateGeneratedFile",
    "CreateGeneratedFileV2",
    "LoadedProposal",
    "OperationPreflightResult",
    "PatchDocument",
    "PatchDocumentV2",
    "PatchHumanFile",
    "PatchOperation",
    "PatchOperationV1",
    "PatchOperationV2",
    "PatchSchemaError",
    "PreflightFinding",
    "PreflightState",
    "ProposalCollectionResult",
    "ProposalLoadFinding",
    "ProposalLoadResult",
    "ProposalMetadata",
    "ProposalPreflightResult",
    "ProposalRisk",
    "ProposalSchemaError",
    "ProposalStatus",
    "ReplaceGeneratedFile",
    "ReplaceGeneratedFileV2",
    "ReleaseGeneratedOwnershipV2",
    "ReplaceManagedBlock",
    "generate_proposal_id",
    "load_proposal_directory",
    "load_proposals",
    "preflight_proposal",
    "serialize_metadata",
    "serialize_patch_document",
    "serialize_patch_json_bytes",
    "validate_metadata",
    "validate_patch_document",
    "validate_proposal_id",
]
from .lifecycle import (
    ProposalTransitionResult,
    TransitionError,
    submit_metadata_for_review,
    approve_metadata,
    reject_metadata,
    submit_proposal_for_review,
    approve_proposal,
    reject_proposal,
)
from .migration import (
    LegacyLifecycleMigrationCandidate,
    LegacyLifecycleMigrationError,
    LegacyLifecycleMigrationPlan,
    LegacyLifecycleMigrationResult,
    migrate_legacy_lifecycle,
    migrate_legacy_metadata,
    migrate_legacy_proposal,
    plan_legacy_lifecycle_migration,
)

from .application import (
    ApplicationError,
    OperationApplicationResult,
    OperationState,
    ProposalApplicationResult,
    apply_proposal,
)

__all__ += [
    "ProposalTransitionResult",
    "TransitionError",
    "submit_metadata_for_review",
    "approve_metadata",
    "reject_metadata",
    "submit_proposal_for_review",
    "approve_proposal",
    "reject_proposal",
    "ApplicationError",
    "OperationApplicationResult",
    "OperationState",
    "ProposalApplicationResult",
    "apply_proposal",
]

__all__ += [
    "LegacyLifecycleMigrationCandidate",
    "LegacyLifecycleMigrationError",
    "LegacyLifecycleMigrationPlan",
    "LegacyLifecycleMigrationResult",
    "migrate_legacy_lifecycle",
    "migrate_legacy_metadata",
    "migrate_legacy_proposal",
    "plan_legacy_lifecycle_migration",
]
