from .loader import (
    LoadedProposal,
    ProposalCollectionResult,
    ProposalLoadFinding,
    ProposalLoadResult,
    load_proposal_directory,
    load_proposals,
)
from .patches import (
    AnyPatchDocument,
    CreateFile,
    CreateGeneratedFile,
    CreateGeneratedFileV2,
    PatchDocument,
    PatchDocumentV2,
    PatchHumanFile,
    PatchOperation,
    PatchOperationV1,
    PatchOperationV2,
    PatchSchemaError,
    ReplaceGeneratedFile,
    ReplaceGeneratedFileV2,
    ReleaseGeneratedOwnershipV2,
    ReplaceManagedBlock,
    serialize_patch_document,
    serialize_patch_json_bytes,
    validate_patch_document,
)
from .schema import (
    ProposalMetadata,
    ProposalRisk,
    ProposalSchemaError,
    ProposalStatus,
    generate_proposal_id,
    serialize_metadata,
    validate_metadata,
    validate_proposal_id,
)
from .review_snapshot import (
    REVIEW_SNAPSHOT_FILENAME,
    REVIEW_SNAPSHOT_SCHEMA_VERSION,
    OperationReviewSnapshot,
    ProposalReviewSnapshot,
    ReviewSnapshotError,
    build_review_snapshot,
    build_review_snapshot_bytes_from_patches,
    operation_unified_diff,
    parse_review_snapshot_bytes,
    serialize_review_snapshot,
    serialize_review_snapshot_bytes,
    validate_review_snapshot,
)
from .target_identity import (
    TARGET_IDENTITY_EXTENSION,
    TARGET_IDENTITY_SCHEMA_VERSION,
    ProposalTargetIdentity,
    ProposalTargetIdentityError,
    assess_proposal_target_identities,
    parse_target_identities,
    with_target_identity_extension,
)
from .validation import (
    OperationPreflightResult,
    PreflightFinding,
    PreflightState,
    ProposalPreflightResult,
)
from . import validation as _validation
from .coherence_validation import preflight_proposal as _coherent_preflight_proposal

# Application imports ``preflight_proposal`` from the validation module below. Install the
# coherence layer first so every application path receives the same fail-closed identity check.
_validation.preflight_proposal = _coherent_preflight_proposal
preflight_proposal = _coherent_preflight_proposal

__all__ = [
    "AnyPatchDocument",
    "CreateFile",
    "CreateGeneratedFile",
    "CreateGeneratedFileV2",
    "LoadedProposal",
    "OperationPreflightResult",
    "PatchDocument",
    "PatchDocumentV2",
    "PatchHumanFile",
    "PatchOperation",
    "PatchOperationV1",
    "PatchOperationV2",
    "PatchSchemaError",
    "PreflightFinding",
    "PreflightState",
    "ProposalCollectionResult",
    "ProposalLoadFinding",
    "ProposalLoadResult",
    "ProposalMetadata",
    "ProposalPreflightResult",
    "ProposalRisk",
    "ProposalReviewSnapshot",
    "ProposalSchemaError",
    "ProposalStatus",
    "ProposalTargetIdentity",
    "ProposalTargetIdentityError",
    "ReplaceGeneratedFile",
    "ReplaceGeneratedFileV2",
    "ReleaseGeneratedOwnershipV2",
    "ReplaceManagedBlock",
    "REVIEW_SNAPSHOT_FILENAME",
    "REVIEW_SNAPSHOT_SCHEMA_VERSION",
    "ReviewSnapshotError",
    "OperationReviewSnapshot",
    "TARGET_IDENTITY_EXTENSION",
    "TARGET_IDENTITY_SCHEMA_VERSION",
    "assess_proposal_target_identities",
    "build_review_snapshot",
    "build_review_snapshot_bytes_from_patches",
    "generate_proposal_id",
    "load_proposal_directory",
    "load_proposals",
    "parse_target_identities",
    "preflight_proposal",
    "operation_unified_diff",
    "parse_review_snapshot_bytes",
    "serialize_metadata",
    "serialize_patch_document",
    "serialize_patch_json_bytes",
    "serialize_review_snapshot",
    "serialize_review_snapshot_bytes",
    "validate_metadata",
    "validate_patch_document",
    "validate_proposal_id",
    "validate_review_snapshot",
    "with_target_identity_extension",
]
from .lifecycle import (
    ProposalTransitionResult,
    TransitionError,
    submit_metadata_for_review,
    approve_metadata,
    reject_metadata,
    submit_proposal_for_review,
    approve_proposal,
    reject_proposal,
)
from .migration import (
    LegacyLifecycleMigrationCandidate,
    LegacyLifecycleMigrationError,
    LegacyLifecycleMigrationPlan,
    LegacyLifecycleMigrationResult,
    migrate_legacy_lifecycle,
    migrate_legacy_metadata,
    migrate_legacy_proposal,
    plan_legacy_lifecycle_migration,
)

from .application import (
    ApplicationError,
    OperationApplicationResult,
    OperationState,
    ProposalApplicationResult,
    apply_proposal,
)

__all__ += [
    "ProposalTransitionResult",
    "TransitionError",
    "submit_metadata_for_review",
    "approve_metadata",
    "reject_metadata",
    "submit_proposal_for_review",
    "approve_proposal",
    "reject_proposal",
    "ApplicationError",
    "OperationApplicationResult",
    "OperationState",
    "ProposalApplicationResult",
    "apply_proposal",
]

__all__ += [
    "LegacyLifecycleMigrationCandidate",
    "LegacyLifecycleMigrationError",
    "LegacyLifecycleMigrationPlan",
    "LegacyLifecycleMigrationResult",
    "migrate_legacy_lifecycle",
    "migrate_legacy_metadata",
    "migrate_legacy_proposal",
    "plan_legacy_lifecycle_migration",
]
